# This is a basic workflow to help you get started with Actions

name: Python application CI test with Github actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'Hello_Python_App/**'
    - '!Flask_ML_Python_App/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ./Hello_Python_App

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run:  make install
        working-directory: ${{env.BUILD_DIR}}
          
      - name: Lint with pylint
        run:  make lint
        working-directory: ${{env.BUILD_DIR}}

      - name: Test with pytest
        run:  make test
        working-directory: ${{env.BUILD_DIR}}


